language: php

php:
  - '7.1'

services:
  - mysql
  - postgresql
  - elasticsearch

addons:
  postgresql: "9.4"
  mysql: "8.0"

before_install:
  - mysql -u root --password="" < provision-scritps/mysql.sql
  - psql -U postgres -f provision-scritps/postgres.sql

before_script:
  - composer self-update
  - composer install
  - sleep 10

script: composer specs